In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
a = torch.empty(2,3)

In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
torch.rand(2,3)

tensor([[0.7730, 0.2169, 0.1781],
        [0.5862, 0.5020, 0.9317]])

In [9]:
torch.rand(2,3)

tensor([[0.6789, 0.8262, 0.4154],
        [0.6540, 0.7823, 0.9288]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [99]:
print("using arange ->", torch.arange(0,10,2))
print("using linspace ->", torch.linspace(0,10,10))
print("using eye ->", torch.eye(5))
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [16]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x)

tensor([[132946479136128, 132946479136128,      4294967295],
        [        7696483,              48,             128]])

In [19]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [21]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Types

In [22]:
x.dtype

torch.int64

In [23]:
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [24]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [25]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

## Mathematical operations

### 1. Scalar operation

In [26]:
x = torch.rand(2,2)
x

tensor([[0.7118, 0.7876],
        [0.4183, 0.9014]])

In [98]:
x + 2
x - 2
x * 3
x / 3
(x * 100)//3
((x * 100)//3)%2
x**2

tensor([[0.5066, 0.6203],
        [0.1750, 0.8125]])

### 2. Element wise operation

In [28]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9969, 0.7565, 0.2239],
        [0.3023, 0.1784, 0.8238]])
tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])


In [97]:
a + b
a - b
a * b
a / b
a ** b
a % b

tensor([[nan, 0., 0.],
        [0., 0., 0.]])

In [30]:
c = torch.tensor([1, -2, 3, -4])

In [36]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [38]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [39]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [40]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [41]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [42]:
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [43]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 0., 7.],
        [0., 0., 9.]])

In [96]:
torch.sum(e)
torch.sum(e, dim=0)
torch.sum(e, dim=1)

tensor([15.,  9.])

In [46]:
torch.mean(e)
torch.mean(e, dim=0)

tensor([4., 0., 8.])

In [47]:
torch.median(e)

tensor(0.)

In [48]:
torch.max(e)
torch.min(e)

tensor(0.)

In [49]:
torch.prod(e)

tensor(0.)

In [50]:
torch.std(e)

tensor(4.4272)

In [51]:
torch.var(e)

tensor(19.6000)

In [52]:
torch.argmax(e)

tensor(5)

In [53]:
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [54]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)
print(f)
print(g)

tensor([[5, 7, 3],
        [9, 4, 0]])
tensor([[5, 7],
        [5, 9],
        [9, 7]])


In [55]:
torch.matmul(f, g)

tensor([[ 87, 119],
        [ 65,  99]])

In [56]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])
torch.dot(vector1, vector2)

tensor(11)

In [57]:
torch.transpose(f, 0, 1)

tensor([[5, 9],
        [7, 4],
        [3, 0]])

In [58]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[5., 9., 8.],
        [9., 7., 9.],
        [2., 6., 7.]])

In [59]:
torch.det(h)

tensor(-110.)

In [60]:
torch.inverse(h)

tensor([[ 0.0455,  0.1364, -0.2273],
        [ 0.4091, -0.1727, -0.2455],
        [-0.3636,  0.1091,  0.4182]])

### 5. Comparison operations

In [64]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 5, 6],
        [2, 9, 5]])
tensor([[0, 4, 2],
        [7, 1, 1]])


In [65]:
i > j
i < j
i == j
i != j

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [66]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[5., 4., 4.],
        [1., 1., 2.]])

In [67]:
torch.log(k)

tensor([[1.6094, 1.3863, 1.3863],
        [0.0000, 0.0000, 0.6931]])

In [68]:
torch.exp(k)

tensor([[148.4132,  54.5981,  54.5981],
        [  2.7183,   2.7183,   7.3891]])

In [69]:
torch.sqrt(k)

tensor([[2.2361, 2.0000, 2.0000],
        [1.0000, 1.0000, 1.4142]])

In [70]:
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.9820],
        [0.7311, 0.7311, 0.8808]])

In [71]:
torch.softmax(k, dim=0)

tensor([[0.9820, 0.9526, 0.8808],
        [0.0180, 0.0474, 0.1192]])

In [72]:
torch.relu(k)

tensor([[5., 4., 4.],
        [1., 1., 2.]])

## Inplace Operations

In [73]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])
tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])


In [74]:
m.add_(n)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [75]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [76]:
n

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [77]:
torch.relu(m)

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [78]:
m.relu_()

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

In [79]:
m

tensor([[1.3361, 0.2472, 1.3114],
        [0.9096, 1.0504, 1.3501]])

## Copying a Tensor

In [80]:
a = torch.rand(2,3)
a

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [81]:
b = a

In [82]:
b

tensor([[0.6594, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [83]:
a[0][0] = 0

In [84]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [85]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [86]:
id(a)

132942575875280

In [87]:
id(b)

132942575875280

In [88]:
b = a.clone()

In [89]:
a

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [90]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [91]:
a[0][0] = 10

In [92]:
a

tensor([[10.0000,  0.0887,  0.4890],
        [ 0.5887,  0.7340,  0.8497]])

In [93]:
b

tensor([[0.0000, 0.0887, 0.4890],
        [0.5887, 0.7340, 0.8497]])

In [94]:
id(a)

132942575875280

In [95]:
id(b)

132942576145936